### ISSUE TITLE
Can't show Sandwiches page

### ISSUE THREAD

**Issue by flifloo** [flifloo/SOD#18]
Page won't load

Logs:
```
Orders" AS "Orders" ON "Orders"."id" = "Orders->SandwichOrder"."OrderId" AND "Orders->SandwichOrder"."date" = '2020-10-01') ON "Sandwich"."name" = "Orders->SandwichOrder"."SandwichName" AND "Orders"."paid" = true GROUP BY "name";
(node:17) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: column "Orders.id" must appear in the GROUP BY clause or be used in an aggregate function
    at Query.formatError (/SOD/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/SOD/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by flifloo** [comment]
Fix on commit [c118f81](https://github.com/flifloo/SOD/commit/c118f81b0a7bd49282dafaa2273f49da157da483)
